apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config             
data:
  default.conf: |
    upstream backend {
      server app-1-svc:8080;
      server app-2-svc:8080;
    }

    server {
        location / {
            proxy_pass http://backend;
        }
    }