apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
spec:
  selector:
    matchLabels:
      app: nginx
      run: my-nginx
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx
        run: my-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 8080
        volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/sites-available/nginx.cfg
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config